// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/ohhfishal/fishy/flashcard"
)

type Flashcard struct {
	Header       string          `json:"header"`
	Description  string          `json:"description"`
	Origin       string          `json:"origin"`
	ClassContext string          `json:"class_context"`
	AiOverview   StringArray     `json:"ai_overview"`
	Thumbnail    flashcard.Image `json:"thumbnail"`
}

type Job struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	Failures  int64     `json:"failures"`
}
