// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"

	"github.com/ohhfishal/fishy/flashcard"
)

const getLastJob = `-- name: GetLastJob :many
SELECT id, created_at, failures FROM jobs
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastJob(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, getLastJob)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Failures); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCard = `-- name: InsertCard :one
INSERT INTO flashcards (
  header,
  description,
  origin,
  class_context,
  ai_overview,
  thumbnail
) values (?, ?, ?, ?, ?, ?)
RETURNING header, description, origin, class_context, ai_overview, thumbnail
`

type InsertCardParams struct {
	Header       string          `json:"header"`
	Description  string          `json:"description"`
	Origin       string          `json:"origin"`
	ClassContext string          `json:"class_context"`
	AiOverview   StringArray     `json:"ai_overview"`
	Thumbnail    flashcard.Image `json:"thumbnail"`
}

func (q *Queries) InsertCard(ctx context.Context, arg InsertCardParams) (Flashcard, error) {
	row := q.db.QueryRowContext(ctx, insertCard,
		arg.Header,
		arg.Description,
		arg.Origin,
		arg.ClassContext,
		arg.AiOverview,
		arg.Thumbnail,
	)
	var i Flashcard
	err := row.Scan(
		&i.Header,
		&i.Description,
		&i.Origin,
		&i.ClassContext,
		&i.AiOverview,
		&i.Thumbnail,
	)
	return i, err
}

const metrics = `-- name: Metrics :one
SELECT
  (SELECT COUNT(*) FROM jobs) as jobs,
  (SELECT COUNT(*) FROM flashcards) as flashcards
`

type MetricsRow struct {
	Jobs       int64 `json:"jobs"`
	Flashcards int64 `json:"flashcards"`
}

func (q *Queries) Metrics(ctx context.Context) (MetricsRow, error) {
	row := q.db.QueryRowContext(ctx, metrics)
	var i MetricsRow
	err := row.Scan(&i.Jobs, &i.Flashcards)
	return i, err
}

const putJob = `-- name: PutJob :one
INSERT INTO jobs (
  failures
) values (?) 
RETURNING id, created_at, failures
`

func (q *Queries) PutJob(ctx context.Context, failures int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, putJob, failures)
	var i Job
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Failures)
	return i, err
}
